# nacos:
host: "127.0.0.1"
# host: "192.168.2.1"
#host: '192.168.3.10'
#host : '192.168.0.109'
port: 8848
namespace: "96bc99f4-1da9-4475-bf3a-f46bf281f1b8"
dataid: "product.json"
group: "DEFAULT_GROUP"



# db:
#   host: "127.0.0.1"
#   port: 3306
#   dbName: "happy_account_mic_training"
#   userName: "root"
#   password: "123456"

# redis:
#   host: "127.0.0.1"
#   port: 6379
#   password: "#foVEYdich"

# consul:
#   host: "192.168.3.10"
#   port: 8500

# account_srv:
#   srvName: "account_srv"
#   host: "192.168.3.10"
#   port: 9095
#   tags:
#     - happy
#     - account_srv

# account_web:
#   srvName: "account_web"
#   host: "192.168.3.10"
#   port: 8081
#   tags:
#     - happy
#     - account_web
